from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)


def generate_pdf_report(result, output_path):
    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        topMargin=0.6 * inch, bottomMargin=0.6 * inch,
        leftMargin=0.7 * inch, rightMargin=0.7 * inch,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleCustom", parent=styles["Title"], fontSize=20,
        textColor=colors.HexColor("#1e293b"), spaceAfter=4,
    )
    heading_style = ParagraphStyle(
        "HeadingCustom", parent=styles["Heading2"], fontSize=13,
        textColor=colors.HexColor("#1e293b"), spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "BodyCustom", parent=styles["Normal"], fontSize=10,
        textColor=colors.HexColor("#334155"), leading=14,
    )
    small_style = ParagraphStyle(
        "SmallCustom", parent=styles["Normal"], fontSize=9,
        textColor=colors.HexColor("#64748b"),
    )

    story = [
        Paragraph("AI Resume Analysis Report", title_style),
        Paragraph(f"Candidate: {result['name']}", body_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0"), spaceAfter=10),
    ]

    score_rows = [
        ["Metric", "Score"],
        ["Overall Resume Score", f"{result['overall_score']} / 100"],
        ["ATS Friendliness Score", f"{result['ats_score']} / 100"],
        ["Readability Score", f"{result['readability_score']} / 100"],
    ]
    if result.get("jd_match"):
        score_rows.append(["Job Description Match", f"{result['jd_match']['match_percentage']}%"])

    score_table = Table(score_rows, colWidths=[3.5 * inch, 2 * inch])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
    ]))
    story.append(score_table)

    story.append(Paragraph("Strengths", heading_style))
    if result["strengths"]:
        for s in result["strengths"]:
            story.append(Paragraph(f"&#10003; {s}", body_style))
    else:
        story.append(Paragraph("No major strengths flagged.", body_style))

    story.append(Paragraph("Priority Improvements", heading_style))
    if result["priority_improvements"]:
        for i, w in enumerate(result["priority_improvements"], 1):
            story.append(Paragraph(f"{i}. {w}", body_style))
    else:
        story.append(Paragraph("No major issues found - well done!", body_style))

    story.append(Paragraph(f"Skills Detected ({len(result['skills'])})", heading_style))
    story.append(Paragraph(", ".join(s.title() for s in result["skills"]) or "None detected", body_style))

    if result.get("soft_skills"):
        story.append(Paragraph("Soft Skills Detected", heading_style))
        story.append(Paragraph(", ".join(s.title() for s in result["soft_skills"]), body_style))

    story.append(Paragraph("Grammar & Writing Quality", heading_style))
    for line in [
        f"Spelling errors found: {len(result['spelling_errors'])}",
        f"Passive voice bullets: {len(result['passive_bullets'])}",
        f"Weak/generic bullets: {len(result['weak_bullets'])}",
        f"Bullets with quantified impact: {result['quant_percentage']}%",
    ]:
        story.append(Paragraph(line, body_style))

    if result.get("jd_match"):
        story.append(Paragraph("Job Description Keyword Match", heading_style))
        jd = result["jd_match"]
        missing_str = ", ".join(jd["missing_keywords"][:10]) or "None"
        story.append(Paragraph(f"Match: {jd['match_percentage']}% | Missing keywords: {missing_str}", body_style))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "Generated by AI Resume Analyzer. Scores are heuristic estimates based on "
        "publicly documented resume best-practices, not a guarantee of ATS/recruiter outcomes.",
        small_style,
    ))

    doc.build(story)
    return output_path
